name: Build

on:
  push:
    branches:
      - main
    pull_requests:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19' # The Go version to download (if necessary) and use.

      - name: Run tests
        run: make test

  tag:
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read version
        run: cat ./version >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v4
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ github.run_number }}",
              sha: context.sha
            })